version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "firday"
      time: "16:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 2
