name: Update Bazel Files
on:
  push:  # Change to push for testing in your fork
    branches:
      - chore/auto-update-bazel-workflow
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: update-bazel-files-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  update:
    name: Update Bazel Files
    # Disable condition when testing in your fork
    # if: >
    #   github.event.pull_request.head.repo.full_name == github.repository ||
    #   github.event.pull_request.maintainer_can_modify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Use default repository and ref for push event
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          fetch-depth: 0
          token: ${{ secrets.BAZEL_PREPARE_PUSH_TOKEN || github.token }}
      - name: Build Prepare
        uses: ./.github/actions/tidb_build
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
      - name: Run Bazel Prepare
        shell: bash
        run: |
          #!/bin/bash
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          make bazel_prepare
      - name: Commit Bazel Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Set correct branch for both push and pull_request_target
          branch: ${{ github.event.pull_request.head.ref || github.ref_name }}
          commit_message: "chore: update bazel file"
          file_pattern: "DEPS.bzl WORKSPACE MODULE.bazel **/*.bazel **/*.bzl"
